- helm/cluster/ci/ci-values.yaml
- helm/cluster/templates/_helpers.tpl
- helm/cluster/templates/clusterapi/_helpers_files.tpl
- helm/cluster/templates/clusterapi/_helpers_flatcar.tpl
- helm/cluster/templates/clusterapi/_helpers_postkubeadmcommands.tpl
- helm/cluster/templates/clusterapi/_helpers_prekubeadmcommands.tpl
- helm/cluster/templates/clusterapi/cluster.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers_files.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_flatcar.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_postkubeadmcommands.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_prekubeadmcommands.tpl
- helm/cluster/templates/clusterapi/controlplane/kubeadmcontrolplane.yaml
- helm/cluster/templates/clusterapi/workers/_helpers_files.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_flatcar.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_joinconfiguration.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_postkubeadmcommands.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_prekubeadmcommands.tpl
- helm/cluster/templates/clusterapi/workers/kubeadmconfig.yaml
- helm/cluster/templates/clusterapi/workers/machinepool.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR adds machine pool resources and all other resources that are required to correctly deploy machine pools (more details here https://github.com/giantswarm/roadmap/issues/2742).
Using this `cluster-$provider` apps will mean that very large portion of machine pools functionality is moved to a common chart.
Common codebase across all providers for (just the highlights):
- Operating system: starting to use this in onprem providers will mean that those providers switch from Ubuntu to Flatcar.
- Config of Kubernetes components: kubelet
- containerd config
- Commands that run before/after kubeadm on nodes
- Kubernetes version
Rendered by CI in one of the next PRs where the CI is fixed:
```
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfig
metadata:
name: awesome-def00 …
```
> Add MachinePool resources

- helm/cluster/templates/clusterapi/controlplane/machinehealthcheck.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR adds MachineHealthCheck resource (more details here https://github.com/giantswarm/roadmap/issues/2742).
The MachineHealthCheck resource has been ported as is from `cluster-aws`, with just Helm values being adjusted for the `cluster` chart.
`cluster-$provider` apps that use `cluster` chart will be able to use MachineHealthCheck for control plane nodes.
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
annotations:
important-cluster-value: 1000
robots-need-this-in-the-cluster: eW91IGNhbm5vdCByZWFkIHRoaXMsIGJ1dCByb2JvdHMgY2FuCg==
labels:
app: cluster
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/version: 0.1.0-dev
application.giantswarm.io/team: turtles
giantswarm.io/cluster: awesome
giantswarm.io/organization: giantswarm …
```
> Add MachineHealthCheck resource

- helm/cluster/ci/ci-values.yaml
- helm/cluster/files/etc/ssh/sshd_config_bastion
- helm/cluster/templates/_helpers.tpl
- helm/cluster/templates/bastion/_helpers.tpl
- helm/cluster/templates/bastion/_helpers_files.tpl
- helm/cluster/templates/bastion/_helpers_flatcar.tpl
- helm/cluster/templates/bastion/_helpers_prekubeadmcommands.tpl
- helm/cluster/templates/bastion/_kubeadmconfigtemplatespec.yaml
- helm/cluster/templates/bastion/kubeadmconfigtemplate.yaml
- helm/cluster/templates/bastion/machinedeployment.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR adds required bastion resources based on Cluster API MachineDeployment (more details here https://github.com/giantswarm/roadmap/issues/2742).
The bastion resources have been ported as is from cluster-aws, with just Helm values being adjusted for the cluster chart.
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
annotations:
helm.sh/resource-policy: keep
important-cluster-value: 1000
robots-need-this-in-the-cluster: eW91IGNhbm5vdCByZWFkIHRoaXMsIGJ1dCByb2JvdHMgY2FuCg==
labels:
cluster.x-k8s.io/role: bastion
app: cluster
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/version: 0.1.0-dev
application.giantswarm.io/team: turtles
giantswarm.io/cluster: awesome
giantswarm.io/organization: giantswarm
giantswarm.io/service-priority: highest …
```
> Add bastion resources

- .github/workflows/zz_generated.json_schema_validation.yaml
- Makefile.gen.cluster_app.mk
- helm/cluster/values.schema.json
The PR normalizes the schema, as until this point it was built without being normalized (fast-paced development, it was changing a lot, and I forgot to run normalization it the whole process).
The PR also disables cluster-app rule-set in schema lint, as that is still not working for the `cluster` chart since it has some assumptions that should be updated (like which top level properties we must have in the schema). We will enable this again when we update the schema linter.
> Normalize schema and disable cluster-app rule-set

- helm/cluster/ci/ci-values.yaml
- helm/cluster/templates/_helpers.tpl
- helm/cluster/templates/bastion/kubeadmconfigtemplate.yaml
- helm/cluster/templates/bastion/machinedeployment.yaml
- helm/cluster/templates/clusterapi/cluster.yaml
- helm/cluster/templates/clusterapi/controlplane/kubeadmcontrolplane.yaml
- helm/cluster/templates/clusterapi/controlplane/machinehealthcheck.yaml
- helm/cluster/templates/clusterapi/workers/kubeadmconfig.yaml
- helm/cluster/templates/clusterapi/workers/machinepool.yaml
- helm/cluster/templates/containerd_config.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR adds feature flags so we can select which resources are templated.
The sole purpose of this is for the initial development so we can incrementally (but quickly) introduce `cluster` chart into `cluster-$provider` apps.
So we can introduce the change in multiple pull requests, e.g.
- A PR that removes Cluster resource in `cluster-aws` and uses Cluster resource from `cluster-chart`
- A PR that removes KubeadmControlPlane resource in `cluster-aws` and uses KubeadmControlPlane resource from `cluster-chart`
- A PR that removes MachinePool and KubeadmConfig resources for node pools in `cluster-aws` and uses MachinePool and KubeadmConfig resources from `cluster-chart`
- etc.
In `cluster-$provider` helm values we will have something like this:
```
cluster:
internal:
resourcesApi: …
```
> Add feature flags to enable/disable resources

- helm/cluster/ci/ci-values.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers.tpl
- helm/cluster/templates/clusterapi/controlplane/kubeadmcontrolplane.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR fixes control plane resources:
- Add missing machine template to KubeadmControlPlane.
Control plane resources are templated correctly.
Updated KubeadmControlPlane resource:
```
/spec  (KubeadmControlPlane/org-giantswarm/awesome)
+ two map entries added:
machineTemplate:
metadata:
labels:
app: cluster
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/version: 0.1.0-dev
application.giantswarm.io/team: turtles
giantswarm.io/cluster: awesome
giantswarm.io/organization: giantswarm
giantswarm.io/service-priority: highest
cluster.x-k8s.io/cluster-name: awesome
cluster.x-k8s.io/watch-filter: capi
helm.sh/chart: cluster-0.1.0-dev
another-cluster-label: label-2
some-cluster-label: label-1
infrastructureRef:
name: awesome-control-plane-f786309f
apiVersion: …
```
> Fix KubeadmControlPlane

- Makefile.development.mk
- helm/cluster/ci/ci-values.yaml
- helm/cluster/files/etc/teleport.yaml
- helm/cluster/files/opt/teleport-node-role.sh
- helm/cluster/templates/clusterapi/_helpers_files.tpl
- helm/cluster/templates/clusterapi/_helpers_flatcar.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_flatcar.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_flatcar.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR adds Teleport support that was originally added in cluster-aws here https://github.com/giantswarm/cluster-aws/pull/334.
Teleport can be optionally enabled.
`cluster` chart Helm values to enable Teleport:
```
internal:
teleport:
enabled: true
```
- https://github.com/giantswarm/roadmap/issues/2742
- https://github.com/giantswarm/cluster-aws/pull/334
Check if the Teleport has been ported properly from cluster-aws.
We don't yet have proper docs for the `cluster` chart.
We have yet to write proper release notes for the `cluster` chart. For now it's just about porting stuff over from `cluster-aws`, so we will add a summary before the first release.
> Add Teleport support

- helm/cluster/ci/ci-values.yaml
- helm/cluster/files/etc/containerd/config.toml
- helm/cluster/files/etc/teleport.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
Updating global property names so they are the same as in cluster-aws.
> Make schema compatible with cluster-aws

- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_apiserver.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR changes schema validation so it is less strict when validating OIDC and proxy. This change is done because `schemalint` currently does fully support using JSON schema with `oneOf`, `if` and `then`.
- Schema validation works in the CI.
- OIDC and proxy properties are not validated in the schema and it's easier to provide incorrect Helm values.
See files diff.
> Make schema less strict

- helm/cluster/templates/clusterapi/workers/machinepool.yaml
Setting the same annotation as we have in `cluster-aws`
> Manage machinepools by cluster-autoscaler

- CHANGELOG.md
- helm/cluster/files/etc/containerd/config.toml
Fixed a small typo in containerd config that would cause it to break in newer flatcar versions (see https://github.com/giantswarm/cluster-aws/pull/421).
> Fixed containerd configuration for newer flatcar

- CHANGELOG.md
- helm/cluster/templates/_helpers.tpl
Fixes a typo in app label deprecation notice.
> Fix typo in app label deprecation notice

- CHANGELOG.md
- Makefile.development.mk
- helm/cluster/README.md
- helm/cluster/templates/clusterapi/cluster.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
Adds a new value - `global.controlPlane.apiServer`. This configures the public facing port for the API on the LoadBalancer
New value, also changes the default from 6443 to 443 on CAPA.
N/A
https://github.com/giantswarm/roadmap/issues/3055
Make sure e2e tests pass. Agree on the value name.
It's a new value so probably yes?
Yes
> Allow configuring cluster api server port

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/ci/test-dummy-values.yaml
- helm/cluster/ci/test-required-values.yaml
- helm/cluster/templates/clusterapi/_helpers.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_apiserver.tpl
- helm/cluster/values.schema.json
Towards https://github.com/giantswarm/roadmap/issues/3047
This PR aligns Helm values API for properties that can be set as pre-defined static values and/or via templates.
Before:
```
connectivity:
proxy:
noProxy:
addresses:
- elb.amazonaws.com
- 169.254.169.254
addressesTemplate: "providerNoProxyTemplateName"
...
apiAudiences:
templateName: "providerApiAudiencesTemplateName"
```
After:
```
connectivity:
proxy:
noProxy:
value:
- elb.amazonaws.com
- 169.254.169.254
templateName: "providerNoProxyTemplateName"
...
apiAudiences:
templateName: "providerApiAudiencesTemplateName"
```
https://github.com/giantswarm/cluster-aws/pull/479#discussion_r1455427379
> Align API for properties that can be set as pre-defined static values and/or via templates

- CHANGELOG.md
- helm/cluster/files/etc/systemd/http-proxy.conf
- helm/cluster/templates/clusterapi/_helpers.tpl
- helm/cluster/templates/clusterapi/_helpers_prekubeadmcommands.tpl
Towards https://github.com/giantswarm/roadmap/issues/3047
Coming from https://github.com/giantswarm/cluster-aws/pull/479#discussion_r1455411843
This PR does few things:
- It renames NO_PROXY template from `cluster.internal.kubeadm.proxy.noProxyList` to `cluster.connectivity.proxy.noProxy`
- So this named template is not internal anymore, and now it can be considered public API offered by the cluster chart.
- It refactors the `cluster.connectivity.proxy.noProxy` template so it can be correctly called from other charts (e.g. render NO_PROXY value in cluster-aws).
Developers from provider-integration KaaS teams can use `cluster.connectivity.proxy.noProxy` template to render NO_PROXY value consistently in their charts.
Example usage when inlcuded in the cluster chart:
```
{{ include …
```
> Improve NO_PROXY template

- CHANGELOG.md
- helm/cluster/templates/clusterapi/_helpers.tpl
Fix "cluster.connectivity.proxy.noProxy" template to correctly render values from specified template (a bug was introduced in https://github.com/giantswarm/cluster/pull/50).
NO_PROXY is correctly rendered.
https://github.com/giantswarm/cluster-aws/pull/479#discussion_r1455411843
> Fix cluster.connectivity.proxy.noProxy template

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/templates/clusterapi/_helpers_files.tpl
- helm/cluster/templates/clusterapi/_helpers_postkubeadmcommands.tpl
- helm/cluster/templates/clusterapi/_helpers_prekubeadmcommands.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_apiserver.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_etcd.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_files.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_initconfiguration.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_joinconfiguration.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_postkubeadmcommands.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_prekubeadmcommands.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_files.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_postkubeadmcommands.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_prekubeadmcommands.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR moves advanced properties that can be customised for every cluster to `.Values.internal.advancedConfiguration`. These advanced properties are currently in `.Values.providerIntegration`, which is incorrect, because `.Values.providerIntegration` is meant to be immutable and set statically (hard-coded) only in Helm `values.yaml` in cluster-\<provider\> apps.
Changes:
- Move `extraCertificateSANs` property to `.Values.internal.advancedConfiguration.controlPlane.apiServer`.
- Move API server `extraArgs` Helm value to `.Values.internal.advancedConfiguration.controlPlane.apiServer`.
- Move API server `etcdPrefix` Helm value to `.Values.internal.advancedConfiguration.controlPlane.apiServer`.
- Move API server `bindPort` Helm value to …
> Move customisable advanced properties to Values.internal.advancedConfiguration

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/templates/clusterapi/controlplane/kubeadmcontrolplane.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This got merged in cluster-aws https://github.com/giantswarm/cluster-aws/pull/482, so we need the same change now in the cluster chart as well, so we don't revert cluster-aws change when we merge https://github.com/giantswarm/cluster-aws/pull/479 because cluster chart is still using the old registries.
See diff.
- https://github.com/giantswarm/cluster-aws/pull/479
- https://github.com/giantswarm/cluster-aws/pull/482
- https://github.com/giantswarm/roadmap/issues/3108
> Use gsoci.azurecr.io registry

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_etcd.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
Towards: https://github.com/giantswarm/roadmap/issues/2977
We want to add the possibility to adjust the etcd quota backend bytes up to 16GiB.
> Add etcd quota backend bytes config

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/templates/clusterapi/cluster.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_apiserver.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
`Sets policy.giantswarm.io/psp-status: disabled` on the Cluster CR. This is needed for upgrading to kubernetes 1.25
None, this is just necessary for upgrading to 1.25
Towards https://github.com/giantswarm/roadmap/issues/2925
no
> Add podSecurityStandards.enforced

- CHANGELOG.md
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_etcd.tpl
Towards https://github.com/giantswarm/roadmap/issues/3047
Quote all etcd extra args, so they are correctly set as strings.
Before:
```yaml
local:
extraArgs:
listen-metrics-urls: "http://0.0.0.0:2381/"
quota-backend-bytes: 17179869184
initial-cluster: "default=http://localhost:2380/"
initial-cluster-state: "existing"
max-snapshots: 3
snapshot-count: 50000
experimental-peer-skip-client-san-verification: true
```
After:
```yaml
local:
extraArgs:
listen-metrics-urls: "http://0.0.0.0:2381"
quota-backend-bytes: "17179869184"
initial-cluster: "default=http://localhost:2380"
initial-cluster-state: "existing"
max-snapshots: "3"
snapshot-count: "50000"
experimental-peer-skip-client-san-verification: "true"
```
We found this bug in failed e2e tests https://github.com/giantswarm/cluster-aws/pull/479.
> Fix etcd extraArgs type

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/templates/bastion/_helpers.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR updates the Kubernetes version to v1.25.16 🎉
<details>
<summary>Plus a small 🧹 change to fix test Helm template that is used in the CI.</summary>
Remove labels from `<provider>MachineTemplate` spec, because the template should contain only spec without metadata.
Metadata changes with every release, so prevuously, when we hashed the template to construct a resource name, the hash would change with every release, meaning that resource name was changing with every release. Because of this every new release was causing incorrect Helm template rendering diff in the GithHub action.
</details>
cluster-\<provider\> apps that use cluster chart will use Kubernetes v1.25.16.
See diff.
Kubernetes version has been updated to 1.25.16 in cluster-aws …
> Update Kubernetes version to 1.25.16

- CHANGELOG.md
- Makefile.development.mk
- helm/cluster/ci/test-required-values.yaml
- helm/cluster/templates/clusterapi/controlplane/machinehealthcheck.yaml
Towards https://github.com/giantswarm/roadmap/issues/3047
Fix MachineHealthCheck annotation rendering issue discovered in https://github.com/giantswarm/cluster-aws/pull/497
MachineHealthCheck annotation rendering works correctly when custom annotations are not specified.
See diff.
https://github.com/giantswarm/cluster-aws/pull/497
> Fix MachineHealthCheck annotation rendering

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/templates/clusterapi/controlplane/kubeadmcontrolplane.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR introduces a new field in the Helm values called `rolloutBefore`. It can be used to control how many days before the expiration of control plane certificates should the control plane nodes be rolled. This mechanism is used by CAPI to ensure that control plane certificates are renewed automatically.
It ensures that certificates on control plane nodes are rotated automatically.
There is a new field available in Values:
```yaml
internal:
advancedConfiguration:
controlPlane:
rolloutBefore: # this structure is taken from CAPI
certificatesExpiryDays: 180 # 180 is the default value
```
It is added to the `KubeadmControlPlane` CR.
Towards: https://github.com/giantswarm/roadmap/issues/3147
Check if the new property located in the correct section of the Helm Values and possibly also test …
> Added support for RolloutBefore field in KubeadmControlPlane

- CHANGELOG.md
- helm/cluster/files/etc/audit/rules.d/99-default.rules
- helm/cluster/templates/clusterapi/_helpers_files.tpl
Towards: https://github.com/giantswarm/giantswarm/issues/27954
Overrides the default audit rules as happens in Vintage clusters
Customers were using our overriden audit configuration, so we need feature parity in CAPI.
> Overridde default audit rules as in Vintage

- CHANGELOG.md
- helm/cluster/templates/clusterapi/controlplane/_helpers_flatcar.tpl
Adds a systemd unit to defragment the local etcd server.
The unit is disabled by default but it is triggered hourly by a timer (every hour at 53:40 minutes, to stagger it from other hourly cronjobs and help identify issues).
Towards feature parity with vintage (mentioned in https://github.com/giantswarm/giantswarm/issues/27954)
> Add systemd unit and timer for hourly etcd defrag.

- helm/cluster/templates/clusterapi/controlplane/_helpers_flatcar.tpl
Fixes the etcd3 defrag service: `crictl ps --name` is a regex, and in clusters where there is another pod that has "etcd" in the name (e.g., `etcd-kubernetes-resources-count-exporter`), in some cases we didn't get the etcd pod id from crictl, causing the service to fail (no other impact on the cluster though).
This makes sure we get the right pod.
> Fixes crictl ps --name regex for etcd pod in etcd3-defragmentation.service

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/ci/test-required-values.yaml
- helm/cluster/templates/clusterapi/_helpers_flatcar.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_flatcar.tpl
- helm/cluster/templates/clusterapi/workers/_helpers.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_flatcar.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_joinconfiguration.tpl
- helm/cluster/templates/clusterapi/workers/kubeadmconfig.yaml
- helm/cluster/templates/clusterapi/workers/machinepool.yaml
- helm/cluster/values.schema.json
Towards https://github.com/giantswarm/roadmap/issues/3194
This PR ports cluster-aws node pool fix from https://github.com/giantswarm/cluster-aws/pull/457.
Other fixes:
- Include `/var/lib/kubelet` directly by default in Ignition on worker nodes.
- Include `/etc/apiserver-environment` environment file in `kubeadm` systemd unit only on control plane nodes.
Node pools will roll correctly when an upgrade that requires that is performed.
See diff.
- https://github.com/giantswarm/cluster-aws/pull/457
- https://github.com/giantswarm/roadmap/issues/3194
> Fix node pool templates

- CHANGELOG.md
- helm/cluster/templates/clusterapi/controlplane/_helpers_joinconfiguration.tpl
Joining control plane nodes, i.e. the 2nd, 3rd and newly rolling nodes didn't have the `--node-ip` kubelet argument. For https://github.com/giantswarm/roadmap/issues/3183 (Cilium ENI mode for AWS), this meant that certain tooling may fail to connect to/through those instances since their kubelet port 10250 would only be available on eth0 (= primary IP), not for example on other network interfaces such as the pod network / pod IPs (eth1 and up in case of ENI mode). Specifically, I observed `kubectl exec` to be broken if it chose the wrong IP of a control plane node, and thus also `cilium connectivity test` would fail since it uses that functionality.
I verified that worker nodes (in machine pools) and the first control plane ("init", not "join" config) have this set correctly.
Tested with …
> Set `--node-ip` kubelet argument also for joining control plane nodes

- helm/cluster/README.md
- helm/cluster/values.schema.json
Related to https://github.com/giantswarm/roadmap/issues/3183, but required in general in order to update `cluster-aws` to `cluster-v0.8.0` (I think). The parent chart, e.g. `cluster-aws` can have provider-specific apps such as `awsCloudControllerManager`, `awsEbsCsiDriver` or `cilium`, and since `global.apps.*` is shared with the `cluster` chart, its schema must allow those keys.
`additionalProperties=false` won't catch typos anymore since any app name is now allowed (e.g. `global.apps.coreDns` vs. `global.apps.CoReDnS` can't be caught). If that's not desired, we have to explicitly list every possible provider-specific app here, or move those to another key such as `global.providerSpecificApps`.
Implementation detail, so I did not consider a public changelog entry. Should I, for our own …
> Allow any app configurations from parent chart in schema

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/templates/clusterapi/_helpers_files.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_files.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_files.tpl
- helm/cluster/values.schema.json
Towards https://github.com/giantswarm/roadmap/issues/3183
Tested together with my cluster-aws change to introduce ENI mode for Cilium.
That requires configuring a certain dynamic config file on the host. We found that using the `contentFrom` (= from Secret) feature was the only reasonable option to pass the file content to the `cluster` chart.
None, since the new field is optional. A value of `contentFrom.secret.prependClusterNameAsPrefix=true` transforms the secret name. This is because the parent chart (e.g. `cluster-aws`) cannot pass dynamic values down that easily, so prepending the already-known cluster name is an easy solution. We have many objects whose name is `<cluster name>-something`, so this is quite usual.
> Support prepending cluster name to file secret name

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/files/etc/kubernetes/patches/kubeletconfiguration.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR makes `containerLogMaxSize` & `containerLogMaxFiles` of Kubelet configurable.
None. Both parameters are not being rendered by default. If they are set, they affect the log rotation behavior of Kubelet.
Towards https://github.com/giantswarm/roadmap/issues/3002.
> Kubelet: Add `containerLogMaxSize` & `containerLogMaxFiles`.

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/files/etc/kubernetes/policies/audit-policy.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers_files.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR makes the audit policy rules we already define extendable by customer defined rules.
The user can define additional audit policy rules which get added to the top of the list of default rules in the audit policy file.
Towards https://github.com/giantswarm/roadmap/issues/3002.
> API Server: Make audit policy rules extendable.

- README.md
Closes https://github.com/giantswarm/roadmap/issues/3195
This PR adds cluster chart docs. This initial version of the docs mostly focuses on provider integration, i.e. the integration of the cluster chart into a cluster-\<provider\> app.
KaaS engineers can more easily work with cluster chart.
See the docs :)
https://github.com/giantswarm/roadmap/issues/3195
It's all about that here :)
No.
> Add cluster chart docs

- CHANGELOG.md
- helm/cluster/templates/clusterapi/controlplane/_helpers_prekubeadmcommands.tpl
Fixes empty `initial-cluster`
```
containers:
- command:
- etcd
- --advertise-client-urls=https://10.1.12.59:2379
- --cert-file=/etc/kubernetes/pki/etcd/server.crt
- --client-cert-auth=true
- --data-dir=/var/lib/etcd
- --experimental-initial-corrupt-check=true
- --experimental-peer-skip-client-san-verification=true
- --experimental-watch-progress-notify-interval=5s
- --initial-advertise-peer-urls=https://10.1.12.59:2380
- --initial-cluster=
- --initial-cluster-state=existing
```
```
{"level":"fatal","ts":"2024-02-28T08:25:52.29194Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"couldn't find local name \"ip-10-1-12-59.eu-central-1.compute.internal\" in the initial cluster configuration","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\tgo.etcd.io/et …
```
> Fix order of preKubeadmCommands for CAPA migration

- CHANGELOG.md
- helm/cluster/templates/apps/cilium.yaml
Includes https://github.com/giantswarm/cilium-app/pull/148, towards https://github.com/giantswarm/roadmap/issues/3183
None for default clusters. This only applies to ENI mode (certain customers will use that, for CAPA it's in prototype status with https://github.com/giantswarm/cluster-aws/pull/528).
Be aware that a second, unrelated change happened in cilium-app v0.21.0: https://github.com/giantswarm/cilium-app/pull/149.
> Update cilium-app to v0.21.0 in order to support Cilium ENI mode for CAPA

- helm/cluster/templates/clusterapi/controlplane/_helpers_files.tpl
`cluster.internal.kubeadm.files.kubernetes` has been used for control plane nodes only and therefore should be in the according namespace. I also split the separate files by topic like we already do in [`cluster.internal.kubeadm.files`](https://github.com/giantswarm/cluster/blob/main/helm/cluster/templates/clusterapi/_helpers_files.tpl#L1) in [`helm/cluster/templates/clusterapi/_helpers_files.tpl`](https://github.com/giantswarm/cluster/blob/main/helm/cluster/templates/clusterapi/_helpers_files.tpl).
> Chart: Split `cluster.internal.kubeadm.files.kubernetes` into `cluster.internal.controlPlane.kubeadm.files.*`.

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/files/etc/kubernetes/admission/config.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_apiserver.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_files.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR makes admission plugins configurable. This is required for porting the PodNodeSelector admission plugin from Vintage.
https://github.com/giantswarm/roadmap/issues/3002
> Chart: Make admission plugins configurable.

- CHANGELOG.md
- helm/cluster/templates/apps/cleanup-helmreleases-hook-job.yaml
Fixes a small typo on the role for the cleanup-helmreleases-hook job that prevented it from being able to patch helmreleases, i.e.:
```
+ kubectl patch -n org-daniel helmrelease.helm.toolkit.fluxcd.io/dan01-network-policies --type=merge -p {"metadata": {"finalizers": []}}
Error from server (Forbidden): helmreleases.helm.toolkit.fluxcd.io "dan01-network-policies" is forbidden: User "system:serviceaccount:org-daniel:dan01-cleanup-helmreleases-hook" cannot patch resource "helmreleases" in API group "helm.toolkit.fluxcd.io" in the namespace "org-daniel"
```
> Fixed typo on cleanup helmreleases role that prevented patching

- CHANGELOG.md
- helm/cluster/templates/apps/network-policies.yaml
Update network-policy app to v0.1.0
None
Same
For https://github.com/giantswarm/roadmap/issues/3261
> Update network-policy app to v0.1.0

- CHANGELOG.md
- helm/cluster/templates/apps/cilium.yaml
Signed-off-by: Matias Charriere <matias@giantswarm.io>
Update the cilium app to v0.22.0
None
Needed for https://github.com/giantswarm/roadmap/issues/3261
> update cilium to v0.22.0

- CHANGELOG.md
- helm/cluster/files/etc/teleport.yaml
Towards https://github.com/giantswarm/giantswarm/issues/30398
- Add new `ins=` label to all nodes, same value as mc= label
- Removes conditional check for `cluster=` label for MC nodes
- No changes.
Currently, our labels doesn't support listing only MC nodes, because cluster= label is not present on MC nodes, only WC nodes and mc= label is common on all nodes.
In Web UI, we can filter by setting cluster="" but same doesn't work on Terminal tsh client.
```
$ tsh ssh root@mc=gazelle,cluster=
ERROR: invalid label spec: 'mc=gazelle,cluster=', should be 'key=value'
$ tsh ssh root@mc=gazelle,cluster=""
ERROR: invalid label spec: 'mc=gazelle,cluster=', should be 'key=value'
```
(Please link public issues or …
> Update teleport node labels

- CHANGELOG.md
- helm/cluster/templates/apps/cilium.yaml
Towards https://github.com/giantswarm/roadmap/issues/2563
This includes https://github.com/giantswarm/cilium-app/pull/179.
Cilium ENI mode is behind a feature toggle and nobody is using it with CAPA yet, so no visible changes.
> Upgrade cilium-app to v0.23.0 in order to make Cilium ENI mode for CAPA usable

- helm/cluster/templates/apps/vertical-pod-autoscaler-crd.yaml
This reverts commit a294eaedf238a94f1f820146567738801347c5d8 (done by renovate).
We have found issues with the corresponding version of VPA (v1.1.0) and want to bump the CRDs again later.
See problem with newer VPA in https://github.com/giantswarm/roadmap/issues/3421 ([chat](https://gigantic.slack.com/archives/C04TGHDEF/p1713876311738559)).
This unblocks me for releasing `cluster`.
None – this wasn't released yet.
> Revert "Update dependency giantswarm/vertical-pod-autoscaler-crd to v3.1.0 (#147)"

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/templates/clusterapi/controlplane/kubeadmcontrolplane.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
Add OS image to cluster chart schema, so it can be used by cluster-\<provider\> apps.
See diff.
We don't want to have OS image publicly configurable, but we do want to configure it during development and testing.
> Add OS image to cluster chart schema

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/files/etc/containerd/config.toml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
Revert https://github.com/giantswarm/cluster/pull/152 because it introduced invalid containerd config which caused containerd to silently partially fail and not apply registry mirrors config.
containerd config is loaded correctly when creating the clusters.
See above description.
No.
> Revert containerd config changes

- CHANGELOG.md
- helm/cluster/templates/clusterapi/_helpers_prekubeadmcommands.tpl
Towards https://github.com/giantswarm/giantswarm/issues/30770
I observed a problem in kubeadm services because of race condition between containerd and kubeadm services. This fixes the issue.
> Restart containerd before kubeadm

- CHANGELOG.md
- helm/cluster/files/apps/cluster-autoscaler.yaml
Towards https://github.com/giantswarm/giantswarm/issues/30671
Updates cluster-autoscaler-app to 1.27.3-gs9 to use new CPU requests.
> Updates cluster-autoscaler-app to 1.27.3-gs9

- CHANGELOG.md
- helm/cluster/templates/clusterapi/_helpers_files.tpl
- helm/cluster/templates/containerd.yaml
- helm/cluster/templates/containerd_config.yaml
It adds hashes to the names of secrets referenced by `contentFrom` so Cluster API notices them changed rolls nodes.
Nodes getting rolled, so no patch.
https://github.com/giantswarm/roadmap/issues/3414
> containerd: Append content hash to configuration secret name.

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_apiserver.tpl
- helm/cluster/values.schema.json
This PR makes the list of feature gates passed to the API server configurable not only via provider integration but also via values passed to the cluster chart by users.
Users now can configure features gates on their own and do not need to depend on the provider specific cluster chart's defaults.
Closes https://github.com/giantswarm/roadmap/issues/3333.
> API Server: Make feature gates configurable.

- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_apiserver.tpl
Also improve order of additional admission plugins.
This PR makes the feature flag condition also check for `cluster` chart defined feature flags. Additionally it correctly orders the way additional admission plugins are being concatenated, even though this doesn't change the output because they are not overriding each other - at least not yet.
Follow-up of https://github.com/giantswarm/cluster/pull/201.
> API Server: Fix feature flag condition.

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_controllermanager.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This PR makes the list of feature gates passed to the controller manager configurable via values passed to the cluster chart by users.
Users now can configure features gates on their own.
Closes https://github.com/giantswarm/roadmap/issues/3333.
> Controller Manager: Make feature gates configurable.

- CHANGELOG.md
- helm/cluster/templates/clusterapi/_helpers_flatcar.tpl
See https://github.com/giantswarm/cluster-azure/pull/284
> Add network-online.target as dependency for kubeadm

- CHANGELOG.md
- helm/cluster/files/apps/k8s-audit-metrics.yaml
- helm/cluster/files/apps/prometheus-blackbox-exporter.yaml
Fix `prometheus-blackbox-exporter` and `k8s-audit-metrics` apps to use the correct chart name
> fix app chart names

- CHANGELOG.md
- helm/cluster/values.schema.json
Change Helm values validation so that `Values.global.release` object is not yet required.
New Helm value was mistakenly made required here https://github.com/giantswarm/cluster/pull/211.
> Values.global.release object is not yet required

- CHANGELOG.md
- Makefile.development.mk
- helm/cluster/ci/ci-values.yaml
- helm/cluster/files/apps/k8s-audit-metrics.yaml
- helm/cluster/files/apps/prometheus-blackbox-exporter.yaml
- helm/cluster/templates/_helpers.tpl
- helm/cluster/templates/apps/apps.yaml
- helm/cluster/templates/apps/helmreleases.yaml
Towards https://github.com/giantswarm/roadmap/issues/3466
- Use app catalog from the Release CR if new releases are used
- Use app dependencies from the Release CR if new releases are used
- Add missing k8s-audit-metrics dependency (kyverno)
Clusters created with new releases will correctly use app dependencies from the Release CR.
No changes for customers.
https://github.com/giantswarm/roadmap/issues/3466
> Fix app catalog and dependencies for new releases

- CHANGELOG.md
- helm/cluster/files/apps/k8s-audit-metrics.yaml
Restores single dependency for K8s Audit Metrics app.
N/A
The list is not supported yet.
> Restoring single dependency

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/files/etc/kubernetes/patches/kubeletconfiguration.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
Allows disabling kubelet authentication, mainly for migration as it was disabled in Vintage
> Insecure kubelet

- .github/workflows/run-cluster-test-suites.yaml
- .github/workflows/trigger-cluster-test-suites.yaml
Add a placeholder GitHub action (does not make any changes anywhere) to automate testing of cluster chart changes in cluster-aws.
In order to really test this, the GitHub workflow has to be in the main branch, so adding first a workflow that just prints theoretical cluster chart version update in cluster-aws.
CAPA is already GA, CAPZ will be GA soon, and all other providers will also soon start to use cluster chart, so without automated cross-provider testing the risk of issues slipping through cracks due to changes not being tested is very high.
> Placeholder CI for automatically testing cluster chart changes in cluster-<provider> apps

- .github/workflows/cluster-provider-test-pull-request.yaml
- .github/workflows/create-or-update-test-pull-request.yaml
- .github/workflows/trigger-cluster-test-suites.yaml
This PR adds a GitHub workflow that automates creation of test PRs in cluster-aws in order to test cluster chart changes.
The workflow gets triggered for every cluster chart pull request. It has 2 jobs:
1. one to create/update test PRs in cluster-aws
2. one to close cluster-aws PRs when cluster chart PRs are closed/merged.
The job that creates/updates cluster-aws PRs will do the following (simplified steps):
- Clone cluster-aws repo.
- Create a new cluster-aws branch called `test-cluster-chart-pr-{{ cluster chart PR number }}`. If the branch already existed it just checks out that branch.
- Update cluster chart version in `test-cluster-chart-pr-{{ cluster chart PR number }}` branch by setting it to a cluster chart version from the tested cluster chart PR.
- Open/update cluster-aws draft …
> Automate cluster-aws test pull requests

- CHANGELOG.md
- README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_controllermanager.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_scheduler.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_initconfiguration.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_joinconfiguration.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_joinconfiguration.tpl
This PR removes the `CronJobTimeZone` feature gate as it becomes stable and is included in Kubernetes v1.29.
For Kubernetes <v1.29, you will need to re-enable it using the respective values.
> Feature Gates: Remove `CronJobTimeZone`.

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/templates/_helpers.tpl
- helm/cluster/values.schema.json
This PR adds `cluster.os.tooling.version` helper which is used to obtain the OS tooling (capi-image-builder) version that is then used to build the OS image name.
Also it adds few new and align names of existing OS-related named templates:
- `cluster.os.name` - new named template that returns the operating system name (fixed return value "flatcar").
- `cluster.os.releaseChannel` - new named template that returns the operating system release channel. It returns `.Values.providerIntegration.osImage.channel` which is "stable" by default for all providers (Helm value was already there, just the template is added here).
- `cluster.os.version` - just calls `cluster.component.flatcar.version` (while `cluster.component.flatcar.version` is marked as deprecated).
Giant Swarm engineers can add and …
> Add OS tooling named template

- helm/cluster/README.md
Add missing Hem value reference in the docs. :see_no_evil: 
Missed it in this PR https://github.com/giantswarm/cluster/pull/288.
No.
> Fix cluster.os.version template docs

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/values.schema.json
This PR deprecates the usage of `.Values.global.connectivity.network.allowAllEgress`.
Currently the default flag value is `false`, which means that `network-policies` app will get installed, which is desired. Setting this flag to true means that `network-policies` app is not installed, and we shouldn't disable network-policies like that anymore.
Public API (global Helm value) that can disable netowork-policies app has been deprecated and should not be used anymore.
Had more than few chats about network policies with KaaS folks. It all started here https://github.com/giantswarm/roadmap/issues/3125.
It looks like that the transition to Cilium network policies has left quite a few leftover configs across multiple (cluster-\<provider\>) apps.
I will open a similar PR in cluster-aws and …
> Deprecate .Values.global.connectivity.network.allowAllEgress

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/files/helmreleases/cilium.yaml
- helm/cluster/templates/clusterapi/_helpers_users.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
Decouples creation of the `giantswarm` user on nodes from the bastion machinedeployment.
Nothing - the original chart behaviour is retained and the new behaviour is disabled by default (requires the provider chart integration to enable it on a per-cluster basis).
CAPV and CAPVCD may not use the bastion machinedeployment as the bastions are often managed outside of the provider charts, however we still need the `giantswarm` user to exist on the nodes.
> Add toggle to enable creation of giantswarm user on nodes

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/files/etc/kubernetes/patches/kube-controller-manager0+json.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers_files.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
This allows setting the `node-cidr-mask-size` flag. The default is `/24` networks, however vintage default is `/25` which may create issues when migrating
None on existing users, default is the same.
There is an addition value now.
N/A
N/A
The docs in the readme have been updated, not sure how they relate to the giantswarm docs at the moment.
Yes
> Allow configuring `node-cidr-mask-size` flag on `kube-controller-manager`

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/files/etc/kubernetes/patches/kube-controller-manager0+json.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers_files.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
See https://github.com/giantswarm/cluster/pull/320
> Allow configuring node-cidr-mask-size flag on kube-controller-manager

- CHANGELOG.md
- helm/cluster/templates/clusterapi/workers/_helpers_joinconfiguration.tpl
I've seen a workload cluster that got created without setting `customNodeLabels`, and the kubelet arguments look like this (notice the trailing comma)
```
healthz-bind-address: 0.0.0.0
node-ip: ${COREOS_EC2_IPV4_LOCAL}
node-labels: ip=${COREOS_EC2_IPV4_LOCAL},role=worker,giantswarm.io/machine-pool=fer01-nodepool0,
v: "2"
```
With the change in this PR, the `customNodeLabels` are only appended to the argument if they are defined.
Users can now skip setting the `customNodeLabels` field, and there won't be a trailing comma in the kubelet arguments.
> Only use customNodeLabels if it's set

- CHANGELOG.md
- helm/cluster/templates/bastion/_helpers_flatcar.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_flatcar.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_flatcar.tpl
Passes the root Template object into the generated dictionary used to template the systemd `additionalFields` value out.
None, this is required to pass CI tests (ABS chart linting)
N/A
Provider charts template out successfully locally, however when the chart linting steps are carried out in CI (on the provider chart), they fail with the following error:
```
[ERROR] templates/: template: cluster-cloud-director/charts/cluster/templates/clusterapi/workers/machinedeployment.yaml:38:79: executing "cluster-cloud-director/charts/cluster/templates/clusterapi/workers/machinedeployment.yaml" at <include "cluster.internal.workers.kubeadmConfig.spec.hash" $>: error calling include: template: cluster-cloud-director/charts/cluster/templates/clusterapi/workers/_helpers.tpl:2:12: executing …
```
> Pass Template object through to generated systemd unit values

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/templates/clusterapi/_helpers_flatcar.tpl
- helm/cluster/values.schema.json
Adds support for Upholds within unit section of custom systemd config
N/A
N/A
Required for cluster-cloud-director provider chart
> Added support for Upholds within unit section of custom systemd configuration

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_apiserver.tpl
- helm/cluster/values.schema.json
Added support for `groupsPrefix` and `usernamePrefix` OIDC flags.
N/A
N/A
This feature is actively used by a cloud-director customer.
> Added support for groupsPrefix and usernamePrefix to OIDC configuration

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/test-cgroupsv1-values.yaml
- helm/cluster/files/etc/containerd/controlplane-config.toml
- helm/cluster/files/etc/containerd/workers-config.toml
- helm/cluster/templates/clusterapi/_helpers_files.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_files.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_initconfiguration.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_joinconfiguration.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_files.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_joinconfiguration.tpl
- helm/cluster/templates/containerd.yaml
- helm/cluster/values.schema.json
Backport of https://github.com/giantswarm/cluster/pull/348
> Allow to configure cgroupsv1 per nodepool

- .github/workflows/cluster-provider-test-pull-request.yaml
Changes how the latest release is fetched in the cluster-provider-test-pull-request GitHub Workflow. It now uses `gh`
```
$ gh view --help
View information about a GitHub Release.
Without an explicit tag name argument, the latest release in the project
is shown.
...
```
My other PR did not work because other releases had been created that were not marked as latest
> Determine latest release using gh for provider test PR

- CHANGELOG.md
- helm/cluster/files/etc/teleport.yaml
Towards: https://github.com/giantswarm/roadmap/issues/3797
Changes `Teleport's` data directory to `/` to prevent login issues when `/var/lib` fills up.
> set teleport data_dir: /teleport

- .github/workflows/cluster-provider-test-pull-request.yaml
Fix problems when having backticks in the PR title, for instance (see [chat](https://gigantic.slack.com/archives/C3S23JE75/p1734086977451249))
No
> GitHub: Fix escaping of PR title in workflow.

- CHANGELOG.md
- helm/cluster/templates/_helpers.tpl
Fail chart deployment instead of deploying this if a (new) application isn't listed in `Release.spec.apps`:
```
sourceRef:
kind: HelmRepository
name: mycluster-
```
Invalid `Release`s can't even be deployed 👍 
No change
I came here from a failing E2E test whose base `Release` didn't have the new aws-node-termination-handler application, as expected ([comment](https://github.com/giantswarm/cluster-aws/pull/945#issuecomment-2523133158)). I'd rather have a hard error and easy-to-troubleshoot E2E test that searching for an empty string deep within the YAML jungle.
No
> Helpers: Fail `cluster.app.catalog` if the app is not listed in the release.

- CHANGELOG.md
- helm/cluster/templates/apps/helmreleases.yaml
- Set `spec.install.remediation.retries` to `-1` from previous `30`
- Set `spec.upgrade.remediation.retries` to `-1`. This wasn't set at all previously
This is a follow up to PR https://github.com/giantswarm/cluster/pull/394 for https://github.com/giantswarm/roadmap/issues/3664
> Set install and upgrade retries of HelmReleases to -1

- .github/workflows/cluster-provider-test-pull-request.yaml
Towards https://github.com/giantswarm/giantswarm/issues/32276 / follow-up from https://github.com/giantswarm/cluster/pull/405. One more value to escape
No
No
> Escape PR branch name in workflow

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/32461
Each node in the cluster will take less pods.
On vintage we used 25, so we wan to keep using it.
> Make nodeCidrMaskSize default to 25

- CHANGELOG.md
- helm/cluster/files/apps/external-dns.yaml
Signed-off-by: Matias Charriere <matias@giantswarm.io>
remove source config from external-dns values
Default value changed in the latest app, but this is overriding.
> Apps: Remove source config from external-dns defaults.

- CHANGELOG.md
- helm/cluster/files/etc/containerd/workers-config.toml
- helm/cluster/tests/components/files/containerd_expected_with_cgroupsv1.toml
- helm/cluster/tests/components/files/containerd_nodepool_expected_with_cgroupsv1.toml
- helm/cluster/tests/components/files/containerd_nodepool_expected_without_cgroupsv1.toml
I noticed when `nvidia-smi` is called within a container and there might be memory leaks, it might take down the whole node.
Setting `SystemdCgroup = true` will isolate the containers so it doesn't affect the whole node when having issues.
That has been also tested upstream, see https://github.com/flatcar/sysext-bakery/blob/main/create_nvidia_runtime_sysext.sh#L177-L180
> Preventing container with Nvidia runtime taking down the whole node going OOM

- CHANGELOG.md
- README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers_initconfiguration.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_joinconfiguration.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_joinconfiguration.tpl
- helm/cluster/values.schema.json
The most important change is that the `value` attribute of a taint is actually optional, while it was marked as required in our value schema. I also updated the taint templating to use a `with` loop and `toYaml` for rendering the data instead of specifying individual dict keys.
Users will be able to specify node taints without a value.
Taints look slightly different in the rendered output.
Discovered while working on https://github.com/giantswarm/giantswarm/issues/31687
_:sparkles: Good vibes :sparkles:_
I doubt it.
Would be nice.
> Refactor templating of custom node taints

- CHANGELOG.md
- helm/cluster/.helmignore
- helm/cluster/files/helmreleases/cilium.yaml
- helm/cluster/templates/apps/helmreleases.yaml
* Add remediation settings for Cilium HelmRelease
* use hasKey to allow value 0 in remediationRetries
* Update changelog
---------
This is a cherry-pick of PR https://github.com/giantswarm/cluster/pull/498 to include in a patch release
> Add remediation settings for Cilium HelmRelease

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/test-multiple-taint-levels.yaml
- helm/cluster/templates/clusterapi/controlplane/_helpers_initconfiguration.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_joinconfiguration.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_joinconfiguration.tpl
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
Enables setting taints on worker nodes, controller nodes, or all of them, by adding the following values:
* `providerIntegration.kubeadmConfig.taints`
* `providerIntegration.controlPlane.kubeadmConfig.taints`
* `providerIntegration.workers.kubeadmConfig.taints`
These are fed to the `KubeadmConfiguration` for all nodes created through the chart.
Users are able to set default taints on nodes.
Success.
Will enable Phoenix to solve https://github.com/giantswarm/giantswarm/issues/31687.
We discussed this in Slack, so it should be fine. :crossed_fingers: 
Yup, updated the generated docs.
> Enable setting taints on (all/worker/controller) nodes through provider integration

- CHANGELOG.md
- helm/cluster/templates/clusterapi/controlplane/_helpers_initconfiguration.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_joinconfiguration.tpl
This is necessary during disaster recovery scenarios, where we restore an etcd snapshot on a running cluster and we need to restart the kubelet to register an existing CP node to the recovered cluster state. Without this the CP node would get registered without the taint, allowing any Pod to get scheduled on it.
For context, normally this taint is added automatically by `kubeadm init` or `kubeadm join`, which will just proceed normally if it's already added by the kubelet before. Kubeadm is not involved during a DR scenario, since it's not designed to be re-run on an already bootstrapped node.
The CP nodes will roll
Related to https://github.com/giantswarm/giantswarm/issues/30439
> Configure the kubelet to register CP nodes with the node-role.kubernetes.io/control-plane taint

- CHANGELOG.md
- helm/cluster/files/helmreleases/cilium.yaml
Right now, cilium uses the external public hostname of the cluster to access the API server. This makes a critical internal component dependant on the baseDomain DNS infrastructure, which is sometimes managed by the customer, sometimes managed by us, and could be unreliable. Additionally it makes baseDomain more rigid and difficult to change on an existing cluster.
When setting `k8sServiceHost: auto`, the cilium helm chart will fetch the k8s API hostname from the `cluster-info` ConfigMap in the `kube-public` Namespace, which is set to an internal hostname or IP inside the provider network (e.g. the ELB hostname in AWS and Azure).
None
https://gigantic.slack.com/archives/CLPMFRVU6/p1752252511295269
> Configure cilium to use the k8s hostname defined in cluster-info CM

- CHANGELOG.md
- helm/cluster/values.schema.json
This change addresses an issue, which popped up after upgrading Helm to v3.18.5+ in MC Bootstrap.
https://tekton.ci.giantswarm.io/#/namespaces/mc-bootstrap/pipelineruns/pr-1354-generate-mc-capz-goose-nxr4f?pipelineTask=generate-mc&step=generate-mc
Since `cluster-azure` is not using `nodePoolKind: MachinePool`, the conditions in the schema do not evaluate to define the `infrastructureMachinePool` property and so this is not known when trying to install the chart in MC Bootstrap.
But since we are using the `infrastructureMachinePool` property in both cases - `nodePoolKind: MachinePool` and `nodePoolKind: MachineDeployment` everywhere in the code, I moved `infrastructureMachinePool` to the previous conditions so it gets defined.
> Values: Fix schema.

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
For a long time, docker hub shouldn't be used at all to pull our images: they introduced harsh rate limiting and high prices to increase them, so we switched to `gsoci.azurecr.io` entirely. If any image from dockerhub is needed, it should be first copied to our registry using `retagger` and then pulled from `gsoci.azurecr.io`. As such, we should remove any mirroring for docker hub. Also, the whole `giantswarm.azurecr.io` registry is considered legacy and will be deleted in the future.
Someone more knowledgeable about cluster deployments: please review this, taking into scope the impact on containerd's configuration and a risk that some cluster images might still come from docker hub.
Related - [issue tracking last images not pulled from …
> Chart: Obsolete default config with mirroring for Docker Hub registry.

- CHANGELOG.md
- helm/cluster/README.md
- helm/cluster/ci/ci-values.yaml
- helm/cluster/files/apps/capi-node-labeler.yaml
- helm/cluster/values.schema.json
- helm/cluster/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/33938
From now on, the worker nodes won't have the `node-role.kubernetes.io/worker` or `node.kubernetes.io/worker` labels.
We've checked all WCs and found no customers relying on these worker labels, so we've decided to remove them. Our own apps using them have been changed already to use alternative methods when needed.
We are planning on releasing this as a new major release of the cluster chart and the provider charts, and including those in v33.
> Remove capi-node-labeler app

- CHANGELOG.md
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_apiserver.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_controllermanager.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_initconfiguration.tpl
- helm/cluster/templates/clusterapi/controlplane/_helpers_joinconfiguration.tpl
- helm/cluster/templates/clusterapi/workers/_helpers_joinconfiguration.tpl
This flag got removed in Kubernetes v1.33.0 and should therefore only be rendered in lower versions.
> Chart: Render `cloud-provider` flag for Kubernetes < v1.33.0 only.
