helm/cluster/README.md, helm/cluster/values.schema.json
Updates the description on the field added in #42. Since the value is confusing, a bit more details won't hurt.
_Not sure it's really necessary_
=> Update apiServerPort description

helm/cluster/templates/clusterapi/_helpers_files.tpl, helm/cluster/templates/clusterapi/controlplane/_helpers_files.tpl, helm/cluster/templates/clusterapi/workers/_helpers_files.tpl
=> Rename `cluster.processFiles` to `cluster.internal.processFiles`

CHANGELOG.md, helm/cluster/values.schema.json
=> Chart: Make `additionalAdmissionPlugins` a reusable definition.

CHANGELOG.md, helm/cluster/templates/clusterapi/controlplane/_helpers_initconfiguration.tpl, helm/cluster/templates/clusterapi/controlplane/_helpers_joinconfiguration.tpl, helm/cluster/templates/clusterapi/workers/_helpers_joinconfiguration.tpl
Towards: https://github.com/giantswarm/roadmap/issues/3339
=> Add node label ip to kubelet

CHANGELOG.md, helm/cluster/templates/clusterapi/_helpers_flatcar.tpl
Towards: https://github.com/giantswarm/roadmap/issues/3342
=> Drop sshkeys service

helm/cluster/templates/apps/helmrepositories.yaml
Reverts giantswarm/cluster#189
=> Revert "Update dependency HelmRepository to source.toolkit.fluxcd.io/v1"

CHANGELOG.md, helm/cluster/templates/clusterapi/workers/machinehealthcheck.yaml, helm/cluster/values.schema.json
Fixes setting the right name for nodepool MachineDeployment health checks.
=> Fix machinehealth for deployments

CHANGELOG.md, helm/cluster/README.md, helm/cluster/values.schema.json
=> Fix RegExp to allow forward slash in labels

CHANGELOG.md, helm/cluster/values.schema.json
=> version non required

CHANGELOG.md, helm/cluster/README.md, helm/cluster/values.schema.json
=> allow empty values in labels

.github/workflows/cluster-provider-test-pull-request.yaml
Minor improvements to PR comment wording.
=> Minor improvements to PR comment wording

CHANGELOG.md, helm/cluster/templates/_helpers.tpl, helm/cluster/templates/apps/helmreleases.yaml, helm/cluster/templates/apps/helmrepositories.yaml, helm/cluster/templates/bastion/machinedeployment.yaml
There were some unnecessary empty lines before and after the labels block.
=> Clean spaces before and after labels block

CHANGELOG.md, helm/cluster/README.md, helm/cluster/values.schema.json
Remove wrong deprecation message.
=> Remove deprecation message for still valid fields

helm/cluster/templates/clusterapi/workers/kubeadmconfig.yaml
=> Update documentation for `KubeadmConfig` name hash

CHANGELOG.md, helm/cluster/README.md, helm/cluster/ci/ci-values.yaml, helm/cluster/templates/_helpers.tpl, helm/cluster/values.schema.json
Back-port of https://github.com/giantswarm/cluster/pull/288.
=> Chart: Add OS tooling named template.

CHANGELOG.md, helm/cluster/templates/clusterapi/_helpers_flatcar.tpl, helm/cluster/templates/clusterapi/workers/_helpers_flatcar.tpl
Fixes https://gigantic.slack.com/archives/C01BYMF6RN0/p1728475037453819?thread_ts=1728472042.225279&cid=C01BYMF6RN0 with https://github.com/giantswarm/cluster-cloud-director/compare/fix-new-line-in-additionalFields?expand=1
=> Fix newline in additionalFields

CHANGELOG.md
Update missing CHANGELOG for PR[#387](https://github.com/giantswarm/cluster/pull/387)
=> Missing CHANGELOG for PR #387

CHANGELOG.md, helm/cluster/README.md, helm/cluster/values.schema.json
@giantswarm/team-honeybadger
@giantswarm/team-cabbage
=> Values: Fix `giantswarm-cluster-suite` and `network-policies` type.

CHANGELOG.md, helm/cluster/files/etc/containerd/workers-config.toml, helm/cluster/tests/components/files/containerd_expected_with_cgroupsv1.toml, helm/cluster/tests/components/files/containerd_expected_without_cgroupsv1.toml, helm/cluster/tests/components/files/containerd_nodepool_expected_with_cgroupsv1.toml, helm/cluster/tests/components/files/containerd_nodepool_expected_without_cgroupsv1.toml, helm/cluster/tests/components/test_containerd_config.go
Towards: https://github.com/giantswarm/adidas/issues/1351
=> Add NVIDIA container runtime support in containerd config

CHANGELOG.md, helm/cluster/files/helmreleases/cilium.yaml, helm/cluster/templates/apps/helmreleases.yaml
Signed-off-by: Matias Charriere <matias@giantswarm.io>
Towards https://github.com/giantswarm/giantswarm/issues/33410
=> Add remediation settings for Cilium HelmRelease
